### ISSUE TITLE
rc.onTheMap() returns null pointer exception given valid parameters

### ISSUE THREAD

**Issue by BrianGuo** [battlecode/battlecode-server#331]
Not entirely sure why this is the case, but I've checked this myself.
calling rc.onTheMap(center, radius) with a valid mapLocation as the center and a valid robot controller will (sometimes, at least) give a null pointer exception. 

The stack trace is here: 
~~~~
java.lang.NullPointerException
        at battlecode.world.RobotControllerImpl.canSenseAllOfCircle(RobotControllerImpl.java:223)
        at battlecode.world.RobotControllerImpl.assertCanSenseAllOfCircle(RobotControllerImpl.java:187)
        at battlecode.world.RobotControllerImpl.onTheMap(RobotControllerImpl.java:203)
        at v1.Gardener.loop(Gardener.java:12)
        at v1.RobotPlayer.run(RobotPlayer.java:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:259)
        at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
        at java.lang.Thread.run(Thread.java:745)
~~~~

I tried creating a gardener to the north of my archon spawn location on the map shrine and immediately called rc.onTheMap, which caused this error

**Comment by BrianGuo** [comment]
Figured out the cause.
Line 223 of RobotControllerImpl:
~~~~
MapLocation furthestPointOnCircle = center.add(center.directionTo(getLocation()).opposite(), radius);
~~~~
center.directionTo(getLocation()) is null because center = getLocation, and directionTo returns null if the two specified locations are the same
This means that anytime you center a circle around your own robot location, this code fails, which is unintuitive

**Comment by Itja** [comment]
This is related to https://github.com/battlecode/battlecode-server/issues/334
