### ISSUE TITLE
Scouts on top of trees sensing nearby trees cause nullpointer exceptions.

### ISSUE THREAD

**Issue by anobit** [battlecode/battlecode-server#334]
Traceback:
`ing 93% > :run
[A:SCOUT#11353@81] Shaking tree @[425.104553, 470.675049]!
[A:SCOUT#11353@83] Throwable got to highest level: java.lang.NullPointerException - null
java.lang.NullPointerException
        at battlecode.common.MapLocation.add(MapLocation.java:257)
        at battlecode.world.RobotControllerImpl.canInteractWithCircle(RobotControllerImpl.java:762)
        at battlecode.world.RobotControllerImpl.canInteractWithTree(RobotControllerImpl.java:940)
        at battlecode.world.RobotControllerImpl.canShake(RobotControllerImpl.java:855)
        at battlecat_anobit.copy.Scout.run(Scout.java:71)
        at battlecat_anobit.copy.RobotPlayer.run(RobotPlayer.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:259)
        at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
        at java.lang.Thread.run(Thread.java:745)
The robot code returned or threw. This really shouldn't happen.`

Once the target location is shifted by 0.1 the exceptions are gone.  toDirection(XX) returns null once target tree and robot are on exactly the same position. This leads to the general NP-Exception in MapLocation.add();

**Comment by Itja** [comment]
This is related to https://github.com/battlecode/battlecode-server/issues/331
