### ISSUE TITLE
InstrumentationException with enhanced for loops

### ISSUE THREAD

**Issue by Pear0** [battlecode/battlecode-server#346]
Minimal test case:
```java
public class RobotPlayer {
    public static void run(RobotController rc) throws GameActionException {

        RobotPlayer[] objects = new RobotPlayer[2];
        for (RobotPlayer o : objects) {
        }

        while (true);
    }
}
```

Exception:
```java
battlecode.instrumenter.InstrumentationException: ILLEGAL Illegal class: testplayerarray/RobotPlayer;
    this class cannot be referenced by player code.
	at battlecode.instrumenter.bytecode.ClassReferenceUtil.classReference(ClassReferenceUtil.java:171)
	at battlecode.instrumenter.bytecode.ClassReferenceUtil.classReference(ClassReferenceUtil.java:150)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.classReference(InstrumentingMethodVisitor.java:78)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.replaceVars(InstrumentingMethodVisitor.java:623)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitFrameNode(InstrumentingMethodVisitor.java:630)
	at battlecode.instrumenter.bytecode.InstrumentingMethodVisitor.visitMaxs(InstrumentingMethodVisitor.java:135)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.instrument(TeamClassLoaderFactory.java:509)
	at battlecode.instrumenter.TeamClassLoaderFactory$Loader.loadClass(TeamClassLoaderFactory.java:430)
	at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:238)
	at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
	at java.lang.Thread.run(Thread.java:745)
```

Notice the `;` in `testplayerarray/RobotPlayer;`

**Comment by axc** [comment]
This might be because we disallow you from using RobotPlayer in your own code.

**Comment by Pear0** [comment]
It causes a similar exception for other objects too when their in the team package, I think it's an issue with ClassReferenceUtil#classReference()'s parsing of array class name strings.

**Comment by Pear0** [comment]
The reason it doesn't fail for Battlecode objects like `RobotInfo` when used in an enhanced for loop is that `RobotInfo` is in the `battlecode.common` package which is in the list of allowed packages. `classReference()` doesn't throw an exception even though the class name is malformed because it calls  `isInAllowedPackage()` which returns true since it only checks the package not the actual class.
